# what language the build will be configured for
language: python

# note that all of the versions listed will be tried
python:
  - "3.5"
  - "3.6"

# what branches should be evaluated
branches:
  only:
    - master

# list of commands to run to setup the environment
install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install flake8
  - pip install -r requirements.txt
  - pip install git+https://github.com/pnnl/darkchem

# a list of commands to run before the main script
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - flake8 darknight --exit-zero  # note for production, the exit-zero should be removed

script:
        #  - pytest
  - coverage run -m pytest darknight

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
